probe-rs/webpage

- templates/index.html
Thanks for all your work on probe-rs! I spotted a small typo in the guide page.
> Typo fix in guide

- templates/index.html
See also: https://riscv.org/risc-v-branding-guidelines-and-materials/
> Fix RISC-V name

- content/cross-dockerfile.txt
- content/guide/4_development/crosscompiling.md
In this PR : 
- Creating a new Page under **4. Development** about crosscompiling `cargo-flash` by using `cross` or `LLVM`
- Adding an Example Dockerfile for `cross` usage
I had an issue with building `cargo-flash` on the **Rasp pi 400**, as it went OOM on the `rustc` linking step.
The Probe-rs Matrix channel was very helpfull and pointed me into the direction of `cross` and `LLVM` targets as options to succesfully overcome this limitation, including an example `Dockerfile`. Now i want to share the knowledge.
While writing the documentation for `LLVM` though, it became apparent that it would require a lof of information about how to use and debug it's toolchain, which made the page go out of context ( in my opinion ). So a link to how someone can use `LLVM` to Crosscompile replaced that …
> Adding Crosscompiling section, Example Dockerfile

- config.toml
- content/docs/library/quickstart.md
- content/docs/tools/cargo-embed.md
- content/docs/tools/cargo-flash.md
- content/docs/tools/vscode.md
- templates/macros/docs-toc.html
Apart from explaining the configuration a bit better, this also converts some HTML to markdown for readability and makes the ToC on the right side properly two-leveled:
| Before: | After |
|---------|-------|
| ![image](https://user-images.githubusercontent.com/933300/171448087-2e87b0c7-b1b0-4f5e-9bbe-92729678745d.png) | ![image](https://user-images.githubusercontent.com/933300/171448121-0dd0e45f-00b4-47ed-b964-d1b09feb71de.png) |
> Expand explanation of cargo embed configuartion a bit (and other little things)

- content/docs/tools/vscode.md
A couple of the config examples had the `chip` and `coreIndex` entries in the wrong place.
> Fix VSCode config examples.

- static/files/cross-dockerfile.txt
Encountered the following error while building Cross using instructions on Cross-building:
`thread 'main' panicked at 'Unable to find libudev: "pkg-config" "--libs" "--cflags" "libudev" did not exit successfully: exit status: 1
`
Found resolution for issue for Ubuntu Linux install to include dependencies, applied same to docker image: [Cargo-embed #338](https://github.com/probe-rs/cargo-embed/pull/338)
> Add missing dependencies libftdi1-dev libudev-dev

- config.toml
This seems to be required by the newest Zola version.
> Add authors taxonomy to config file

- content/docs/tools/vscode.md
- Remove `connectUnderReset: true` from sample configurations. This option is only supported on some platforms and caused confusion for new users.
- Add an `Appendix` to show all available configuration options and their descriptions.
> VSCode doc updates

- static/files/69-probe-rs.rules
This adds two udev rules allowing `plugdev` group access to Espressif USB debuggers. Mostly useful when targeting RISC-V based esp32 chips, like `esp32c3`.
Ref: https://esp-rs.github.io/book/tooling/debugging/probe-rs.html#permissions---linux
> udev: add rules for Espressif USB debuggers

- content/_index.md
Same as https://github.com/probe-rs/probe-rs/pull/1343 on the main repo README.
> Fix CI badge URL

- content/docs/library/quickstart.md
A few small updates to bring the library quickstart docs in line with current probe-rs (0.17.0).
> fix(docs): update library quickstart

- content/docs/tools/vscode.md
Update docs for VSCode extension to match the `probe-rs` 0.19.0 release [changes to the names of the binaries](https://github.com/probe-rs/probe-rs/pull/1637) and [PR #1643](https://github.com/probe-rs/probe-rs/pull/1643).
> Update VSCode docs to match `probe-rs` v0.19.0 binaries

- content/docs/tools/vscode.md
Updates the documentation to reflect the changes in https://github.com/probe-rs/vscode/pull/62 and https://github.com/probe-rs/probe-rs/pull/1656
> VSCode: Add support binary flashing formats

- content/blog/release-0.11.0.md
- content/docs/getting-started/installation.md
- content/docs/getting-started/probe-setup.md
- content/docs/library/quickstart.md
- content/docs/tools/cargo-embed.md
Fix #79 and #83, and update some additional broken links which were found using `zola check`. It unfortunately has some false positives, otherwise it would be nice to run it automatically once a week or so.
> Update outdated links, add missing deps

- content/docs/getting-started/probe-setup.md
J-Link probes now support WinUSB officially, with a guide for how to switch modes if your device wasn't shipped in WinUSB mode (Newer models ship in WinUSB mode by default). Update the instructions to use the official method for switching drivers, which also keeps compatibility with official segger tools.
> Update probe setup docs JLink USB instructions

- content/docs/tools/cargo-flash.md
The docs are outdated here, there is no more `--list-chips` - the equivalent seems to be `probe-rs info`.
This fixes: https://github.com/probe-rs/probe-rs/issues/1736
> docs: fix outdated cli call

- src/docs/getting-started/installation.md
- src/docs/getting-started/probe-setup.md
- Avoid H1 so the table of contents reflects the actual contents
- Better grouping by install method
- Add brew insts
- Fix styling of cargo's box (needed the language spec)
- Separate platform nuances from the probe list
- Clarify that a j-link is not available on ALL evaluation boards
- Update macOS name styling
> Round two with install and probe instructions

- src/docs/getting-started/probe-setup.md
Resolves #117.
I tested the recommendation using a J-Link Compact Plus, and probe-rs was indeed working after installing the WinUSB driver via the J-Link Configurator.
> Update J-Link setup to recommend configurator tool on Windows

- README.md
The initial startup for serving the web page locally takes quite some time. Let's take other young players by hand through this long wait.
> Make development section in README.md more explicit

- src/docs/getting-started/installation.md
- src/docs/library/crosscompiling.md
- src/docs/tools/cargo-embed.md
- src/docs/tools/cargo-flash.md
* Install target folder is now probe-rs-tools
* Fixed dead link to default cargo-embed toml
* Associated PR: https://github.com/probe-rs/probe-rs/pull/2431
> Update docs based on crate restructuring

- src/docs/getting-started/installation.md
We accidentally released to crates.io so we might as well have the instructions in place, too.
> How to install latest release from source

- src/docs/tools/debugger.md
It seems that "format" argument is not longer exists in VSCode extension's settings. Now the extension uses "binaryFormat" instead. 
This PR updates the documentation.
> fix outdated "format" argument in doc

- src/docs/getting-started/installation.md
Give this reference to users at the time of installation installing probe-rs so. It will come in handy for sure. It took me some time to discover this piece of convenience.
> Mention shell completion in install instructions

- src/docs/knowledge-base/troubleshooting.md
- src/docs/tools/debugger.md
Setting an env var in `launch.json` has no effect.
> Update docs around DEFMT_LOG

- src/docs/getting-started/installation.md
The build.rs script of probe-rs-tools is executing the git command.
> Add git to the list of packages to install to build probe-rs-tools

- src/docs/getting-started/installation.md
- src/docs/library/crosscompiling.md
> Recommend --locked

- src/docs/tools/cargo-embed.md
On the cargo-embed website, the tcp-socket image is far too wide on my screen:
> Fix tcp-socket image too wide on cargo-embed docs

- public/files/69-probe-rs.rules
This got removed in the website rework.
> Re-add WCH Link probe
