templates/index.html, templates/macros.html
Link to our subprojects or issue labels in the list of features.
=> Add links to the feature list.

snippets/cargo-flash.sh
It's `--list-chips` not `--list-targets`. The comment also wasn't very clear and could be misunderstood as "list *connected* targets"
=> Clarify cargo flash intro, fix command.

.github/workflows/ci.yml, CNAME, README.md, config.toml
Fix the Zola action to a specific version (0.12).
Also adds the CNAME file in the root directory, to ensure that the custom domain is still used after a deploy.
=> Try fixing CI

content/guide/1_tools/cargo-flash.md
I did the steps on the current website, and got stuck, so let's get it fixed.
=> Add essential info about prerequisites for cargo flash

README.md, content/docs/knowledge-base/raspberry-pi.md
* Add a new topic on Raspberry Pi 4 setup.
* Update README to reflect new version requirements.
=> Add doc on how to setup the Raspberry Pi 4

content/docs/tools/vscode.md
The installation instructions referred to a README.md that refers back to these official docs.
=> Update installation instructions for `probe-rs-debugger`

content/docs/knowledge-base/cmsis-packs.md
To reflect the changes in https://github.com/probe-rs/probe-rs/pull/1259/
=> target-gen: Minor doc edit.

content/docs/tools/vscode.md
Please see (and synchronize merge with): [VSCode PR#37](https://github.com/probe-rs/vscode/pull/37)
=> VSCode doc update to match extension version 0.4.1

content/docs/tools/cargo-embed.md
Just bugged me too much to unsee, sorry for the nanopull...
=> Minor grammar correction

.github/workflows/ci.yml
=> Update zola action

content/docs/knowledge-base/troubleshooting.md
Added troubleshooting page to the knowledge base section. Initially this is troubleshooting DEFMT prints not appearing, but other problems could be added as well!
=> Troubleshooting page

static/files/69-probe-rs.rules
related to https://github.com/probe-rs/probe-rs/pull/1004
=> add WCH-Link CMSIS-DAP rule

src/docs/tools/debugger.md
We're just machines constantly creating memory after memroy.
=> Goodbye memroy

src/docs/knowledge-base/troubleshooting.md
=> Fix location of rttEnabled

src/docs/faq/faq.md
This is in the FAQ just because I'm not sure this is fleshed out enough to warrant a separate page yet, but it should be an OK starting point.
=> Add report FAQ

src/docs/tools/debugger.md
Forgot to do this with the 0.24 changes
=> Update vscode launch config schema

src/targets/_data.js
Needs https://github.com/probe-rs/probe-rs/pull/2585 otherwise deno dies with duplicate entry.
=> Add missing yaml types

src/docs/tools/cargo-embed.md
=> Update cargo-embed example

src/docs/library/basics.md, src/docs/library/quickstart.md
cc https://github.com/probe-rs/probe-rs/issues/2693
I bet this is still largely incorrect but the docs can use any love we give them.
=> Update lib docs

src/docs/library/crosscompiling.md
Updated Cross repo URL to reflect the the move to cross-rs/cross
=> docs: Update Cross repo URL in crosscompiling.md

src/static/files/69-probe-rs.rules
=> Add WCH Link variant

.github/workflows/deploy-preview.yml, .github/workflows/deploy.yml, deno.lock, src/docs/tools/cargo-embed.md
Companion PR of https://github.com/probe-rs/probe-rs/pull/2618, to be merged at next release.
=> Update key bindings

src/components/Head.astro, src/components/HeaderLink.astro, src/icons/hamburger-menu.svg, src/layouts/Html.astro
Added github icon + link, slighly moved the searchbar, added the hamburger menu on mobile with absolute positioning
=> Improved navbar styling

src/content/docs/library/basics.mdx
=> Little typo in Basic Usage prbe -> probe
